config/routes.rb
Trillium::Application.routes.draw do
  
  

  get 'about' => 'pages#about'

  get 'services' => 'pages#services'
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		Trillium Landscaping Design and Landscaping Services
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar nav-tabs navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">Trillium Landscaping</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
						<li>
							<%= link_to 'Services', services_path %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trillium</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header'%>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer'%>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Currently some filler text</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>A view of us</p>
	

app/views/pages/services.html.erb
<h1>Our Services</h1>
<p>Services we offer</p>
<div class="hero-unit" id="galleria">
    <img src="assets/Lavender.jpg">
	<img src="assets/_1030042.jpg">
</div>
<script>
	Galleria.loadTheme("assets/galleria/classic/galleria.classic.min.js");
	Galleria.run('#galleria');
</script>